-- ----------
-- INSERTION
-- ----------

-- CYCLE

--INSERT INTO CYCLE(id, nom) VALUES (CYCLE_ID_SEQ.NEXTVAL, 'Préscolaire');
--INSERT INTO CYCLE(id, nom) VALUES (CYCLE_ID_SEQ.NEXTVAL, 'Primaire');
--INSERT INTO CYCLE(id, nom) VALUES (CYCLE_ID_SEQ.NEXTVAL, 'Secondaire');
INSERT INTO CYCLE(id, nom) VALUES (CYCLE_ID_SEQ.NEXTVAL, 'Supérieur');
COMMIT;

-- NIVEAU

INSERT INTO NIVEAU (id, nom, sigle, cycle_id)
SELECT NIVEAU_ID_SEQ.NEXTVAL, 'Brevet de Technicien Supérieur', 'BTS', id AS cycle_id 
FROM cycle WHERE cycle.nom = 'Supérieur';
COMMIT;

-- CLASSE

INSERT INTO CLASSE (id, nom, niveau_id)
SELECT CLASSE_ID_SEQ.NEXTVAL, 'IDA2/A', id AS niveau_id 
FROM niveau WHERE niveau.nom = 'Brevet de Technicien Supérieur';

INSERT INTO CLASSE (id, nom, niveau_id)
SELECT CLASSE_ID_SEQ.NEXTVAL, 'IDA2/B', id AS niveau_id 
FROM niveau WHERE niveau.nom = 'Brevet de Technicien Supérieur';
COMMIT;

-- ELEVE

INSERT INTO ELEVE(MATRICULE, NOM, PRENOM, SEXE, DATE_NAISSANCE, LIEU_NAISSANCE, NATIONALITE, REGIME, redoublant, interne, affecte, INSCRIPTION_ANNEE_SCOLAIRE, CLASSE_ID)
SELECT '12347','KOFFI','JEAN','M',TO_DATE('15-07-1990','DD-MM-YYYY'),'TOUMODI','IVOIRIENNE','Boursier','O','O','N','2016-2017', id AS classe_id 
FROM classe WHERE classe.nom = 'IDA2/A';

INSERT INTO ELEVE(MATRICULE, NOM, PRENOM, SEXE, DATE_NAISSANCE, LIEU_NAISSANCE, NATIONALITE, REGIME, redoublant, interne, affecte, INSCRIPTION_ANNEE_SCOLAIRE, CLASSE_ID) 
SELECT '29825','AVI','FIDELE WILLY','M',TO_DATE('15-08-1990','DD-MM-YYYY'),'Yopougon','IVOIRIENNE','Boursier','O','N','N','2016-2017', id AS classe_id 
FROM classe WHERE classe.nom = 'IDA2/B';

INSERT INTO ELEVE(MATRICULE, NOM, PRENOM, SEXE, DATE_NAISSANCE, LIEU_NAISSANCE, NATIONALITE, REGIME, redoublant, interne, affecte, INSCRIPTION_ANNEE_SCOLAIRE, CLASSE_ID) 
SELECT '30825','MENIER','CHARLENE','F',TO_DATE('10-07-1992','DD-MM-YYYY'),'COCODY','IVOIRIENNE','Non Boursière','N','O','O','2016-2017', id AS classe_id 
FROM classe WHERE classe.nom = 'IDA2/A';

INSERT INTO ELEVE(MATRICULE, NOM, PRENOM, SEXE, DATE_NAISSANCE, LIEU_NAISSANCE, NATIONALITE, REGIME, redoublant, interne, affecte, INSCRIPTION_ANNEE_SCOLAIRE, CLASSE_ID) 
SELECT '78945','KONE','AICHA','F',TO_DATE('20-11-1995','DD-MM-YYYY'),'KATIOLA','IVOIRIENNE','Boursière','N','N','N','2016-2017', id AS classe_id 
FROM classe WHERE classe.nom = 'IDA2/B';

INSERT INTO ELEVE(MATRICULE, NOM, PRENOM, SEXE, DATE_NAISSANCE, LIEU_NAISSANCE, NATIONALITE, REGIME, redoublant, interne, affecte, INSCRIPTION_ANNEE_SCOLAIRE, CLASSE_ID) 
SELECT '79854','KEYS','ALICIA','F',TO_DATE('10-07-1990','DD-MM-YYYY'),'NEW-YORK','AMERICAINE','Non Boursière','N','O','O','2015-2016', id AS classe_id
FROM classe WHERE classe.nom = 'IDA2/A';

INSERT INTO ELEVE(MATRICULE, NOM, PRENOM, SEXE, DATE_NAISSANCE, LIEU_NAISSANCE, NATIONALITE, REGIME, redoublant, interne, affecte, INSCRIPTION_ANNEE_SCOLAIRE, CLASSE_ID) 
SELECT '5gjf78','AKON','NELSON','M',TO_DATE('17-01-1988','DD-MM-YYYY'),'DAKAR','SENEGALAISE','Boursier','O','N','N','2017-2018', id AS classe_id
FROM classe WHERE classe.nom = 'IDA2/B';
COMMIT;

-- PROFESSEUR 

INSERT INTO PROFESSEUR (id, nom, prenom, adresse, typeprof) VALUES (PROFESSEUR_ID_SEQ.NEXTVAL, 'LIASSOU', 'Muranga', null, 'permanent');
INSERT INTO PROFESSEUR (id, nom, prenom, adresse, typeprof) VALUES (PROFESSEUR_ID_SEQ.NEXTVAL, 'TRAORE', 'Namble', null, 'vacataire');
INSERT INTO PROFESSEUR (id, nom, prenom, adresse, typeprof) VALUES (PROFESSEUR_ID_SEQ.NEXTVAL, 'ADJE', 'Atticora', null, 'vacataire');
INSERT INTO PROFESSEUR (id, nom, prenom, adresse, typeprof) VALUES (PROFESSEUR_ID_SEQ.NEXTVAL, 'TANHI', 'Virginie', null, 'permanent');
INSERT INTO PROFESSEUR (id, nom, prenom, adresse, typeprof) VALUES (PROFESSEUR_ID_SEQ.NEXTVAL, 'ADOPO', 'Frederique', null, 'vacataire');
INSERT INTO PROFESSEUR (id, nom, prenom, adresse, typeprof) VALUES (PROFESSEUR_ID_SEQ.NEXTVAL, 'N''GUESSAN', 'Ble', null, 'permanent');
INSERT INTO PROFESSEUR (id, nom, prenom, adresse, typeprof) VALUES (PROFESSEUR_ID_SEQ.NEXTVAL, 'CRESPIN', 'Mathieu', null, 'permanent');
INSERT INTO PROFESSEUR (id, nom, prenom, adresse, typeprof) VALUES (PROFESSEUR_ID_SEQ.NEXTVAL, 'KOUAKOU', 'K. Denis', null, 'vacataire');
INSERT INTO PROFESSEUR (id, nom, prenom, adresse, typeprof) VALUES (PROFESSEUR_ID_SEQ.NEXTVAL, 'BAKO', 'Roger', null, 'vacataire');
INSERT INTO PROFESSEUR (id, nom, prenom, adresse, typeprof) VALUES (PROFESSEUR_ID_SEQ.NEXTVAL, 'OUATTARA', 'Abou', null, 'vacataire');
INSERT INTO PROFESSEUR (id, nom, prenom, adresse, typeprof) VALUES (PROFESSEUR_ID_SEQ.NEXTVAL, 'BAKAYOKO', 'Vassidiki', null, 'permanent');
INSERT INTO PROFESSEUR (id, nom, prenom, adresse, typeprof) VALUES (PROFESSEUR_ID_SEQ.NEXTVAL, 'BOKA', 'Paul', null, 'permanent');
INSERT INTO PROFESSEUR (id, nom, prenom, adresse, typeprof) VALUES (PROFESSEUR_ID_SEQ.NEXTVAL, 'OUATTARA', 'Abdoulaye', null, 'permanent');
INSERT INTO PROFESSEUR (id, nom, prenom, adresse, typeprof) VALUES (PROFESSEUR_ID_SEQ.NEXTVAL, 'N''GUESSAN', 'Bernard', null, 'permanent');
INSERT INTO PROFESSEUR (id, nom, prenom, adresse, typeprof) VALUES (PROFESSEUR_ID_SEQ.NEXTVAL, 'VANIE', 'Henri', null, 'vacataire');
COMMIT;

-- SESSION

INSERT INTO SESS (id, nom, date_debut, date_fin) VALUES (SESSION_ID_SEQ.NEXTVAL, '1er Semestre', TO_DATE('07-10-2016','DD-MM-YYYY'), TO_DATE('07-02-2017','DD-MM-YYYY'));
INSERT INTO SESS (id, nom, date_debut, date_fin) VALUES (SESSION_ID_SEQ.NEXTVAL, '2eme Semestre', TO_DATE('07-03-2017','DD-MM-YYYY'), TO_DATE('07-07-2017','DD-MM-YYYY'));
COMMIT;

-- MATIERE

INSERT INTO MATIERE (code, libelle) VALUES ('ALGO', 'ALGORITHME');
INSERT INTO MATIERE (code, libelle) VALUES ('BD', 'BASE DE DONNEES');
INSERT INTO MATIERE (code, libelle) VALUES('NEGO INFO', 'NEGOCIATION INFORMATIQUE');
INSERT INTO MATIERE (code, libelle) VALUES ('PROJET', 'PROJET');
INSERT INTO MATIERE (code, libelle) VALUES ('SE', 'SYSTEME EXPLOITATION');
INSERT INTO MATIERE (code, libelle) VALUES ('ANA', 'ANALYSE');
INSERT INTO MATIERE (code, libelle) VALUES ('VB', 'VISUAL BASIC');
INSERT INTO MATIERE (code, libelle) VALUES ('C', 'LANGAGE C');
INSERT INTO MATIERE (code, libelle) VALUES ('PHP', 'LANGAGE PHP');
INSERT INTO MATIERE (code, libelle) VALUES ('TELEINFO', 'RESEAU ET TELEINFORMATIQUE');
INSERT INTO MATIERE (code, libelle) VALUES ('ANGLAIS', 'ANGLAIS');
INSERT INTO MATIERE (code, libelle) VALUES ('FR', 'FRANCAIS');
INSERT INTO MATIERE (code, libelle) VALUES ('ECO', 'ECONOMIE');
INSERT INTO MATIERE (code, libelle) VALUES ('MATH GENE', 'MATHEMATIQUE GENERALE');
INSERT INTO MATIERE (code, libelle) VALUES ('MATH FIN', 'MATHEMATIQUE FINANCIERE');
INSERT INTO MATIERE (code, libelle) VALUES('DROIT', 'DROIT');
INSERT INTO MATIERE (code, libelle) VALUES('COMPTA', 'COMPTABILITE');
INSERT INTO MATIERE (code, libelle) VALUES('ASSIDUTE', 'ASSIDUTE');
INSERT INTO MATIERE (code, libelle) VALUES('CONDUITE', 'CONDUITE');
COMMIT;

-- RELEVE

INSERT INTO RELEVE (id, session_id)
SELECT RELEVE_ID_SEQ.NEXTVAL, id AS session_id 
FROM sess WHERE sess.nom = '1er Semestre';

INSERT INTO RELEVE (id, session_id) 
SELECT RELEVE_ID_SEQ.NEXTVAL, id AS session_id 
FROM sess WHERE sess.nom = '1er Semestre';

INSERT INTO RELEVE (id, session_id) 
SELECT RELEVE_ID_SEQ.NEXTVAL, id AS session_id 
FROM sess WHERE sess.nom = '2eme Semestre';

INSERT INTO RELEVE (id, session_id) 
SELECT RELEVE_ID_SEQ.NEXTVAL, id AS session_id 
FROM sess WHERE sess.nom = '2eme Semestre';

INSERT INTO RELEVE (id, session_id) 
SELECT RELEVE_ID_SEQ.NEXTVAL, id AS session_id 
FROM sess WHERE sess.nom = '1er Semestre';
COMMIT;

-- NOTE

-- relevés 1er semestre 
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 15.00, 17.00, 13.00, null, null, '29825', 'ALGO', 1);
INSERT INTO NOTE VALUES  (NOTE_ID_SEQ.NEXTVAL, 7.00, 9.00, 8.00, null, null, '29825', 'ANA', 1);
INSERT INTO NOTE VALUES  (NOTE_ID_SEQ.NEXTVAL, 7.50, 13.00, 13.00, null, null, '29825', 'ANGLAIS', 1);
INSERT INTO NOTE VALUES  (NOTE_ID_SEQ.NEXTVAL, 18.00, null, null, null, null, '29825', 'ASSIDUTE', 1);
INSERT INTO NOTE VALUES  (NOTE_ID_SEQ.NEXTVAL, 15.00, null, null, null, null, '29825', 'CONDUITE', 1);
INSERT INTO NOTE VALUES  (NOTE_ID_SEQ.NEXTVAL, 12.00, 18.50, 9.00, null, null, '29825', 'BD', 1);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 18.00, 6.00, 11.00, null, null, '29825', 'C', 1);
INSERT INTO NOTE VALUES  (NOTE_ID_SEQ.NEXTVAL, 11.00, 18.00, 7.00, null, null, '29825', 'COMPTA', 1);
INSERT INTO NOTE VALUES  (NOTE_ID_SEQ.NEXTVAL, 13.00, 9.00, 10.00, null, null, '29825', 'DROIT', 1);
INSERT INTO NOTE VALUES  (NOTE_ID_SEQ.NEXTVAL, 10.00, 15.00, 4.50, null, null, '29825', 'ECO', 1);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 6.00, 11.00, 9.00, null, null, '29825', 'FR', 1);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 9.00, 12.00, 9.00, null, null, '29825', 'MATH FIN', 1);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 6.00, 6.00, 12.00, null, null, '29825', 'MATH GENE', 1);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 11.00, 7.00, 15.00, null, null, '29825', 'NEGO INFO', 1);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 16.00, 8.00, 8.50, null, null, '29825', 'PHP', 1);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 13.00, 14.50, 12.00, null, null, '29825', 'PROJET', 1);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 13.00, 9.00, 14.00, null, null, '29825', 'SE', 1);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 7.00, 4.00, 11.00, null, null, '29825', 'TELEINFO', 1);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 17.00, 10.00, 14.00, null, null, '29825', 'VB', 1);

INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 15.00, 17.00, 10.00, null, null, '30825', 'ALGO', 2);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 7.00, 9.00, 8.00, null, null, '30825', 'ANA', 2);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 7.50, 13.00, 13.00, null, null, '30825', 'ANGLAIS', 2);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 18.00, null, null, null, null, '30825', 'ASSIDUTE', 2);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 15.00, null, null, null, null, '30825', 'CONDUITE', 2);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 12.00, 18.50, 9.00, null, null, '30825', 'BD', 2);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 18.00, 6.00, 11.00, null, null, '30825', 'C', 2);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 11.00, 18.00, 7.00, null, null, '30825', 'COMPTA', 2);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 13.00, 9.00, 10.00, null, null, '30825', 'DROIT', 2);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 10.00, 15.00, 4.50, null, null, '30825', 'ECO', 2);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 6.00, 11.00, 9.00, null, null, '30825', 'FR', 2);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 9.00, 12.00, 9.00, null, null, '30825', 'MATH FIN', 2);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 6.00, 6.00, 12.00, null, null, '30825', 'MATH GENE', 2);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 11.00, 7.00, 15.00, null, null, '30825', 'NEGO INFO', 2);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 16.00, 8.00, 8.50, null, null, '30825', 'PHP', 2);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 13.00, 14.50, 12.00, null, null, '30825', 'PROJET', 2);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 13.00, 9.00, 14.00, null, null, '30825', 'SE', 2);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 7.00, 4.00, 11.00, null, null, '30825', 'TELEINFO', 2);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 17.00, 10.00, 14.00, null, null, '30825', 'VB', 2);

-- relevés 2ème semestre 
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 15.00, 17.00, 10.00, null, null, '78945', 'ALGO', 3);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 7.00, 9.00, 8.00, null, null, '78945', 'ANA', 3);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 7.50, 13.00, 13.00, null, null, '78945', 'ANGLAIS', 3);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 18.00, null, null, null, null, '78945', 'ASSIDUTE', 3);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 15.00, null, null, null, null, '78945', 'CONDUITE', 3);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 12.00, 18.50, 9.00, null, null, '78945', 'BD', 3);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 18.00, 6.00, 11.00, null, null, '78945', 'C', 3);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 11.00, 18.00, 7.00, null, null, '78945', 'COMPTA', 3);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 13.00, 9.00, 10.00, null, null, '78945', 'DROIT', 3);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 10.00, 15.00, 4.50, null, null, '78945', 'ECO', 3);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 6.00, 11.00, 9.00, null, null, '78945', 'FR', 3);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 9.00, 12.00, 9.00, null, null, '78945', 'MATH FIN', 3);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 6.00, 6.00, 12.00, null, null, '78945', 'MATH GENE', 3);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 11.00, 7.00, 15.00, null, null, '78945', 'NEGO INFO', 3);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 16.00, 8.00, 8.50, null, null, '78945', 'PHP', 3);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 13.00, 14.50, 12.00, null, null, '78945', 'PROJET', 3);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 13.00, 9.00, 14.00, null, null, '78945', 'SE', 3);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 7.00, 4.00, 11.00, null, null, '78945', 'TELEINFO', 3);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 17.00, 10.00, 14.00, null, null, '78945', 'VB', 3);

INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 15.00, 17.00, 13.00, null, null, '79854', 'ALGO', 4);
INSERT INTO NOTE VALUES  (NOTE_ID_SEQ.NEXTVAL, 7.00, 9.00, 8.00, null, null, '79854', 'ANA', 4);
INSERT INTO NOTE VALUES  (NOTE_ID_SEQ.NEXTVAL, 7.50, 13.00, 13.00, null, null, '79854', 'ANGLAIS', 4);
INSERT INTO NOTE VALUES  (NOTE_ID_SEQ.NEXTVAL, 18.00, null, null, null, null, '79854', 'ASSIDUTE', 4);
INSERT INTO NOTE VALUES  (NOTE_ID_SEQ.NEXTVAL, 15.00, null, null, null, null, '79854', 'CONDUITE', 4);
INSERT INTO NOTE VALUES  (NOTE_ID_SEQ.NEXTVAL, 12.00, 18.50, 9.00, null, null, '79854', 'BD', 4);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 18.00, 6.00, 11.00, null, null, '79854', 'C', 4);
INSERT INTO NOTE VALUES  (NOTE_ID_SEQ.NEXTVAL, 11.00, 18.00, 7.00, null, null, '79854', 'COMPTA', 4);
INSERT INTO NOTE VALUES  (NOTE_ID_SEQ.NEXTVAL, 13.00, 9.00, 10.00, null, null, '79854', 'DROIT', 4);
INSERT INTO NOTE VALUES  (NOTE_ID_SEQ.NEXTVAL, 10.00, 15.00, 4.50, null, null, '79854', 'ECO', 4);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 6.00, 11.00, 9.00, null, null, '79854', 'FR', 4);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 9.00, 12.00, 9.00, null, null, '79854', 'MATH FIN', 4);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 6.00, 6.00, 12.00, null, null, '79854', 'MATH GENE', 4);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 11.00, 7.00, 15.00, null, null, '79854', 'NEGO INFO', 4);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 16.00, 8.00, 8.50, null, null, '79854', 'PHP', 4);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 13.00, 14.50, 12.00, null, null, '79854', 'PROJET', 4);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 13.00, 9.00, 14.00, null, null, '79854', 'SE', 4);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 7.00, 4.00, 11.00, null, null, '79854', 'TELEINFO', 4);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 17.00, 10.00, 14.00, null, null, '79854', 'VB', 4);

INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 15.00, 17.00, 10.00, null, null, '12347', 'ALGO', 5);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 7.00, 9.00, 8.00, null, null, '12347', 'ANA', 5);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 7.50, 13.00, 13.00, null, null, '12347', 'ANGLAIS', 5);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 18.00, null, null, null, null, '12347', 'ASSIDUTE', 5);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 15.00, null, null, null, null, '12347', 'CONDUITE', 5);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 12.00, 18.50, 9.00, null, null, '12347', 'BD', 5);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 18.00, 6.00, 11.00, null, null, '12347', 'C', 5);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 11.00, 18.00, 7.00, null, null, '12347', 'COMPTA', 5);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 13.00, 9.00, 10.00, null, null, '12347', 'DROIT', 5);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 10.00, 15.00, 4.50, null, null, '12347', 'ECO', 5);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 6.00, 11.00, 9.00, null, null, '12347', 'FR', 5);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 9.00, 12.00, 9.00, null, null, '12347', 'MATH FIN', 5);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 6.00, 6.00, 12.00, null, null, '12347', 'MATH GENE', 5);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 11.00, 7.00, 15.00, null, null, '12347', 'NEGO INFO', 5);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 16.00, 8.00, 8.50, null, null, '12347', 'PHP', 5);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 13.00, 14.50, 12.00, null, null, '12347', 'PROJET', 5);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 13.00, 9.00, 14.00, null, null, '12347', 'SE', 5);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 7.00, 4.00, 11.00, null, null, '12347', 'TELEINFO', 5);
INSERT INTO NOTE VALUES (NOTE_ID_SEQ.NEXTVAL, 17.00, 10.00, 14.00, null, null, '12347', 'VB', 5);

COMMIT;

-- ETABLISSEMENT
INSERT INTO etablissement VALUES ('012116','Ecole Pratique de la Chambre de Commerce et d''Industrie de Côte d''Ivoire (EPCCI-CI)','23 BP 1421 ABIDJAN 23','23 51 88 23','Semi privé','epcci@yahoo.fr');
COMMIT;

-- MATIERE_CLASSE
INSERT INTO MATIERE_CLASSE VALUES ('ALGO', 1, 4);
INSERT INTO MATIERE_CLASSE VALUES ('BD', 1, 2);
INSERT INTO MATIERE_CLASSE VALUES ('NEGO INFO', 1, 2);
INSERT INTO MATIERE_CLASSE VALUES ('PROJET', 1, 2);
INSERT INTO MATIERE_CLASSE VALUES ('SE', 1, 2);
INSERT INTO MATIERE_CLASSE VALUES ('ANA', 1, 4);
INSERT INTO MATIERE_CLASSE VALUES ('VB', 1, 4);
INSERT INTO MATIERE_CLASSE VALUES ('C', 1, 2);
INSERT INTO MATIERE_CLASSE VALUES ('PHP', 1, 4);
INSERT INTO MATIERE_CLASSE VALUES ('TELEINFO', 1, 2);
INSERT INTO MATIERE_CLASSE VALUES ('ANGLAIS', 1, 2);
INSERT INTO MATIERE_CLASSE VALUES ('FR', 1, 2);
INSERT INTO MATIERE_CLASSE VALUES ('ECO', 1, 2);
INSERT INTO MATIERE_CLASSE VALUES ('MATH GENE', 1, 3);
INSERT INTO MATIERE_CLASSE VALUES ('MATH FIN', 1, 2);
INSERT INTO MATIERE_CLASSE VALUES ('DROIT', 1, 2);
INSERT INTO MATIERE_CLASSE VALUES ('COMPTA', 1, 2);
INSERT INTO MATIERE_CLASSE VALUES ('ASSIDUTE', 1, 1);
INSERT INTO MATIERE_CLASSE VALUES ('CONDUITE', 1, 1);
INSERT INTO MATIERE_CLASSE VALUES ('ALGO', 2, 4);
INSERT INTO MATIERE_CLASSE VALUES ('BD', 2, 2);
INSERT INTO MATIERE_CLASSE VALUES ('NEGO INFO', 2, 2);
INSERT INTO MATIERE_CLASSE VALUES ('PROJET', 2, 2);
INSERT INTO MATIERE_CLASSE VALUES ('SE', 2, 2);
INSERT INTO MATIERE_CLASSE VALUES ('ANA', 2, 4);
INSERT INTO MATIERE_CLASSE VALUES ('VB', 2, 4);
INSERT INTO MATIERE_CLASSE VALUES ('C', 2, 2);
INSERT INTO MATIERE_CLASSE VALUES ('PHP', 2, 4);
INSERT INTO MATIERE_CLASSE VALUES ('TELEINFO', 2, 2);
INSERT INTO MATIERE_CLASSE VALUES ('ANGLAIS', 2, 2);
INSERT INTO MATIERE_CLASSE VALUES ('FR', 2, 2);
INSERT INTO MATIERE_CLASSE VALUES ('ECO', 2, 2);
INSERT INTO MATIERE_CLASSE VALUES ('MATH GENE', 2, 3);
INSERT INTO MATIERE_CLASSE VALUES ('MATH FIN', 2, 2);
INSERT INTO MATIERE_CLASSE VALUES ('DROIT', 2, 2);
INSERT INTO MATIERE_CLASSE VALUES ('COMPTA', 2, 2);
INSERT INTO MATIERE_CLASSE VALUES ('ASSIDUTE', 2, 1);
INSERT INTO MATIERE_CLASSE VALUES ('CONDUITE', 2, 1);
COMMIT;

-- Professeur matière
INSERT INTO professeur_matiere (professeur_id, matiere_code, volume_horaire)
SELECT id AS professeur_id, 'ALGO' AS matiere_code, 89
FROM professeur WHERE nom = 'LIASSOU' AND prenom = 'Muranga'
UNION
SELECT id AS professeur_id, 'BD' AS matiere_code, 65
FROM professeur WHERE nom = 'TRAORE' AND prenom = 'Namble'
UNION
SELECT id AS professeur_id, 'NEGO INFO' AS matiere_code, 36
FROM professeur WHERE nom = 'ADJE' AND prenom = 'Atticora'
UNION
SELECT id AS professeur_id, 'PROJET' AS matiere_code, 42
FROM professeur WHERE nom = 'TANHI' AND prenom = 'Virginie'
UNION
SELECT id AS professeur_id, 'SE' AS matiere_code, 47
FROM professeur WHERE nom = 'ADJE' AND prenom = 'Atticora'
UNION
SELECT id AS professeur_id, 'ANA' AS matiere_code, 47
FROM professeur WHERE nom = 'ADJE' AND prenom = 'Atticora'
UNION
SELECT id AS professeur_id, 'VB' AS matiere_code, 47
FROM professeur WHERE nom = 'TANHI' AND prenom = 'Virginie'
UNION
SELECT id AS professeur_id, 'C' AS matiere_code, 47
FROM professeur WHERE nom = 'TANHI' AND prenom = 'Virginie'
UNION
SELECT id AS professeur_id, 'PHP' AS matiere_code, 47
FROM professeur WHERE nom = 'ADOPO' AND prenom = 'Frederique'
UNION
SELECT id AS professeur_id, 'PHP' AS matiere_code, 47
FROM professeur WHERE nom = 'VANIE' AND prenom = 'Henri'
UNION
SELECT id AS professeur_id, 'TELEINFO' AS matiere_code, 47
FROM professeur WHERE nom = 'LIASSOU' AND prenom = 'Muranga'
UNION
SELECT id AS professeur_id, 'ANGLAIS' AS matiere_code, 47
FROM professeur WHERE nom = 'N''GUESSAN' AND prenom = 'Ble'
UNION
SELECT id AS professeur_id, 'FR' AS matiere_code, 47
FROM professeur WHERE nom = 'CRESPIN' AND prenom = 'Mathieu'
UNION
SELECT id AS professeur_id, 'ECO' AS matiere_code, 47
FROM professeur WHERE nom = 'N''GUESSAN' AND prenom = 'Bernard'
UNION
SELECT id AS professeur_id, 'MATH GENE' AS matiere_code, 47
FROM professeur WHERE nom = 'KOUAKOU' AND prenom = 'K. Denis'
UNION
SELECT id AS professeur_id, 'MATH FIN' AS matiere_code, 47
FROM professeur WHERE nom = 'BAKO' AND prenom = 'Roger'
UNION
SELECT id AS professeur_id, 'DROIT' AS matiere_code, 47
FROM professeur WHERE nom = 'OUATTARA' AND prenom = 'Abou'
UNION
SELECT id AS professeur_id, 'COMPTA' AS matiere_code, 47
FROM professeur WHERE nom = 'BAKAYOKO' AND prenom = 'Vassidiki'
UNION
SELECT id AS professeur_id, 'ASSIDUTE' AS matiere_code, 47
FROM professeur WHERE nom = 'BOKA' AND prenom = 'Paul'
UNION
SELECT id AS professeur_id, 'CONDUITE' AS matiere_code, 47
FROM professeur WHERE nom = 'OUATTARA' AND prenom = 'Abdoulaye'
;
COMMIT;

-- USERS
insert into users values (1, 'liassou', 'liassou', 'professeur');
insert into users values (2, 'boka', 'boka', 'educateur');
insert into users values (3, 'kacou', 'kacou', 'directeur des études');
COMMIT;